name: tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  tests: 
    strategy:
      matrix:
        python: [3.8]
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{matrix.python}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python}}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: test
        run: |
          sudo apt-get install expect
          expect -c "set timeout 10; spawn python3 ragnews/__init.py; expect \"ragnews>\"; puts \"Test Passed: 'ragnews>' prompt detected.\"; expect eof"


          
          
          
          
